spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      username: root
      password: root
      url: jdbc:mysql://localhost:3306/mp-test
      driver-class-name: com.mysql.cj.jdbc.Driver


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #控制台输出sql语句
  type-aliases-package: com.tsx.pojo
  global-config:
    db-config:
      id-type: auto #配置主键策略
#      logic-delete-field: deleted
#      logic-delete-value: 1
#      logic-not-delete-value: 0